# MPC参数
receding: 10 # 滚动时域窗口长度，预测未来8个步长的运动轨迹
step_time: 0.15 # 每步时间 (s)
ref_speed: 0.8 # 轨迹跟踪参考线速度，单位m/s
device: 'cpu'
time_print: True  # 是否打印每一步计算耗时，用于性能调试
collision_threshold: 0.05 # 碰撞安全距离阈值

robot:
  kinematics: 'omni'   # 底盘运动学模型，omni为全向轮底盘
  max_speed: [1.0, 1.0] # 最大线速度 [x向最大速度, y向最大速度]，单位m/s
  max_acce: [1.0, 1.0] # 最大线加速度 [x向最大加速度, y向最大加速度]，单位m/s²
  length: 0.42
  width: 0.26

ipath:
  interval: 0.09  # 参考路径插值点间距，diff单位m
  waypoints: [[0.0, 0, 0], [3.5 ,0 , 0]]# 路径关键点
  curve_style: 'line'  # 路径插值类型，line直线
  min_radius: 0  # 路径最小转弯半径，0代表无转弯限制
  loop: False # 是否循环路径，False到达终点即停止，True循环往复
  arrive_threshold: 0.1 # 到达终点判定距离阈值，单位m
  close_threshold: 0.08  # 靠近路径点判定阈值，用于路径点切换
  ind_range: 10
  arrive_index_threshold: 1  # 路径点到达索引阈值，连续N个点达标判定抵达当前路点

pan:
  iter_num: 3  # 单步规划迭代次数
  dune_max_num: 100 # DUNE模型最大采样轨迹数量
  nrmp_max_num: 10   # NRMP优化最大候选轨迹数量
  iter_threshold: 0.1 # 迭代收敛误差阈值，误差小于该值停止迭代
  dune_checkpoint: 'example/mowen/model/mowen_real/model_5000.pth'

adjust:
  q_s: 0.5 # 路径跟踪权重：越大→车越死板地沿着规划路径走，偏离了会用力纠回来
  p_u: 1.0 # 控制代价权重：越大→车越不敢大角度转向/急加速，动作越平滑温和
  eta: 8.0 # 碰撞约束硬度：越大→障碍物像"墙"，车不敢靠近；越小→障碍物像"虚线"，车能贴近
  d_max: 0.3 # DUNE 最大感知距离：DUNE 认为"安全"的最大距离值。越大→车对远处障碍不敏感，敢走近再反应
  d_min: 0.05 # DUNE 最小安全距离：车能接受离障碍物多近。越小→贴得越近才急停
  solver: "SCS" # 求解器: ECOS/SCS/OSQP

